import React, { useEffect } from "react";
import { useAppContext } from "../../context/AppContext";
import { Box, ContentContainer, Text, Divider, Button } from "../../atoms";
import Head from "next/head";
import Link from "next/link";

function Privacity() {
    const { colorPalette } = useAppContext();

    useEffect(() => {
        document.title = `Afectu - Política de Privacidade`;
        return () => window.removeEventListener("resize", () => { });
    }, []);
    

    return (
        <>
            <Head>
                <title>Afectu - Políticas de Privacidade</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                    rel="icon"
                    href="https://minhaclinicatrindade.s3.amazonaws.com/Afectu+-+PNG+-+Fundo+Tranparente-8%402x.png"
                />
            </Head>

            <Box
                sx={{
                    display: "flex",
                    backgroundColor: colorPalette.primary,
                    justifyContent: "center",
                    alignItems: "center",
                    width: "100%",
                    height: "100%",
                    padding: "2rem",
                }}
            >
                <ContentContainer>
                    <Text bold title >
                        Política de Privacidade - Afectu
                    </Text>
                    <Divider />

                    <Text bold large>
                        Termo de Privacidade para Sessões Terapêuticas - Pessoa Física (PF)
                    </Text>

                    <Text>
                        Bem-vindo à Afectu. Antes de iniciar suas sessões terapêuticas conosco, é importante que você leia e compreenda nosso Termo de Privacidade. Este documento estabelece as diretrizes sobre a confidencialidade e o manejo das informações durante o processo terapêutico. Ao aceitar este termo, você concorda com as condições aqui descritas.
                    </Text>

                    <Text bold>1. Confidencialidade</Text>
                    <Text>
                        Todas as informações compartilhadas durante as sessões terapêuticas são estritamente confidenciais. Nós nos comprometemos a proteger sua privacidade e garantir que qualquer dado pessoal ou discussão ocorrida durante as sessões permaneça segura e privada. Apenas em situações previstas por lei, como risco de dano a si mesmo ou a terceiros, seremos obrigados a informar as autoridades competentes.
                    </Text>

                    <Text bold>2. Limitações de Intervenção</Text>
                    <Text>
                        Os terapeutas da Afectu estão aqui para apoiar seu bem-estar emocional e psicológico. No entanto, é importante entender que não temos influência ou controle sobre aspectos externos à terapia, como dinâmicas familiares, profissionais ou sociais. Nosso papel é fornecer um espaço seguro para reflexão e crescimento pessoal.
                    </Text>

                    <Text bold>3. Não Gravação das Sessões</Text>
                    <Text>
                        Para proteger sua privacidade e garantir um ambiente seguro e aberto, as sessões terapêuticas não podem ser gravadas, seja por áudio, vídeo ou qualquer outro meio. Isso se aplica tanto ao terapeuta quanto ao cliente. Ao aceitar este termo, você concorda em não registrar as sessões de nenhuma forma.
                    </Text>

                    <Text bold>4. Aceitação do Termo</Text>
                    <Text>
                        Ao iniciar suas sessões terapêuticas com a Afectu, você confirma que leu, entendeu e concorda com os termos de privacidade aqui estabelecidos. Caso tenha alguma dúvida ou necessite de esclarecimentos adicionais, sinta-se à vontade para discutir com seu terapeuta antes da primeira sessão.
                    </Text>

                    <Text bold>5. Alterações no Termo</Text>
                    <Text>
                        A Afectu reserva-se o direito de modificar este Termo de Privacidade a qualquer momento. Qualquer alteração será comunicada a você com antecedência, e sua continuidade nas sessões implicará na aceitação das novas condições.
                    </Text>

                    <Text>
                        <strong>Contato:</strong> Se você tiver dúvidas ou preocupações sobre este Termo de Privacidade, entre em contato conosco pelo e-mail contato@afectu.com ou pelo WhatsApp +55 11 91654-4375.
                    </Text>

                    <Divider />

                    <Text bold large>
                        Termo de Privacidade para Sessões Terapêuticas - Pessoa Jurídica (PJ)
                    </Text>

                    <Text>
                        Bem-vindo à Afectu. Antes de iniciar suas sessões terapêuticas conosco, é importante que você leia e compreenda nosso Termo de Privacidade. Este documento estabelece as diretrizes sobre a confidencialidade e o manejo das informações durante o processo terapêutico. Ao aceitar este termo, você concorda com as condições aqui descritas.
                    </Text>

                    <Text bold>1. Confidencialidade</Text>
                    <Text>
                        Todas as informações compartilhadas durante as sessões terapêuticas são estritamente confidenciais. Nós nos comprometemos a proteger sua privacidade e garantir que qualquer dado pessoal ou discussão ocorrida durante as sessões permaneça segura e privada. Apenas em situações previstas por lei, como risco de dano a si mesmo ou a terceiros, seremos obrigados a informar as autoridades competentes.
                    </Text>

                    <Text bold>2. Gestão da Empresa</Text>
                    <Text>
                        Questões ou preocupações relacionadas à gestão da empresa devem ser direcionadas exclusivamente aos seus superiores diretos dentro da Afectu. Não é permitido discutir assuntos internos da empresa durante as sessões terapêuticas, a menos que estejam diretamente relacionados ao seu bem-estar emocional ou psicológico.
                    </Text>

                    <Text bold>3. Não Gravação das Sessões</Text>
                    <Text>
                        Para proteger sua privacidade e garantir um ambiente seguro e aberto, as sessões terapêuticas não podem ser gravadas, seja por áudio, vídeo ou qualquer outro meio. Isso se aplica tanto ao terapeuta quanto ao cliente. Ao aceitar este termo, você concorda em não registrar as sessões de nenhuma forma.
                    </Text>

                    <Text bold>4. Aceitação do Termo</Text>
                    <Text>
                        Ao iniciar suas sessões terapêuticas com a Afectu, você confirma que leu, entendeu e concorda com os termos de privacidade aqui estabelecidos. Caso tenha alguma dúvida ou necessite de esclarecimentos adicionais, sinta-se à vontade para discutir com seu terapeuta antes da primeira sessão.
                    </Text>

                    <Text bold>5. Alterações no Termo</Text>
                    <Text>
                        A Afectu reserva-se o direito de modificar este Termo de Privacidade a qualquer momento. Qualquer alteração será comunicada a você com antecedência, e sua continuidade nas sessões implicará na aceitação das novas condições.
                    </Text>

                    <Text>
                        <strong>Contato:</strong> Se você tiver dúvidas ou preocupações sobre este Termo de Privacidade, entre em contato conosco pelo e-mail contato@afectu.com ou pelo WhatsApp +55 11 91654-4375.
                    </Text>

                    <Divider />

                    <Box sx={{ display: "flex", justifyContent: "center", marginTop: "2rem" }}>
                        <Link href="/login">
                            <Button text="Voltar para Login ou Registrar"
                                sx={{ backgroundColor: colorPalette.secondary, color: "#fff", padding: "0.75rem 1.5rem" }}
                            />

                        </Link>
                    </Box>

                </ContentContainer>
            </Box>
        </>
    );
}

export default Privacity;
