import Head from 'next/head'
import { Box } from '../atoms'
import { useAppContext } from '../context/AppContext'
import { ProtectRoute } from '../context/ProtectRoute'
import { Colors, LeftMenu, UserHeader } from '../organisms'
// import { menuItems } from '../permissions'
import '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { api } from '../api/api'
import { Elements } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';

const PagesRoute = ({ Component, pageProps }) => {

    const { colorPalette } = useAppContext()
    const removePadding = Component.noPadding;
    const stripePromise = loadStripe('pk_test_51OhxFfKKgBAGSCie1RiVGz6iupTDZy7I276AqK8g2T6MTf4yyaIxNuLrFkq47lM7uPtTjTwVoXJi6vJRJXDHzGcE00TruZBp9y');

    return (
        <>
            <Head>
                <title>Afectu</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta charset="utf-8" />
                <link rel="icon" href="https://minhaclinicatrindade.s3.amazonaws.com/Afectu+-+PNG+-+Fundo+Tranparente-8%402x.png" />
            </Head>
            <ProtectRoute>
                <Box sx={{ ...styles.bodyContainer, backgroundColor: colorPalette.primary }}>
                    <LeftMenu />
                    <UserHeader />
                    <Box sx={{
                        ...styles.contentContainer, backgroundColor: colorPalette.primary, transition: 'background-color 1s',
                        padding: removePadding ? '0px' : { xs: `30px 5px 85px 5px`, xm: `25px`, md: `120px 65px`, lg: `120px 65px` }
                    }}>
                        <Elements stripe={stripePromise}>
                            <Component {...pageProps} />
                        </Elements>
                    </Box>
                </Box>
            </ProtectRoute>
        </>
    )
}

const styles = {
    bodyContainer: {
        display: "flex",
        minHeight: "100vh",
        flexDirection: "row",
        width: '100%',
    },
    contentContainer: {
        display: "flex",
        width: '100%',
        flexDirection: 'column',
        flex: 1,
        gap: `35px`,
        paddingBottom: `60px`,
        overflowY: 'hidden',
        marginTop: { xs: `60px`, xm: `0px`, md: `0px`, lg: `0px` }
    },
}

export default PagesRoute;