import Head from 'next/head'
import { Box } from '../atoms'
import { useAppContext } from '../context/AppContext'
import { ProtectRoute } from '../context/ProtectRoute'
import { Colors, LeftMenu, UserHeader } from '../organisms'
import '../styles/Home.module.css'
import { TabNavigator } from '../organisms/layout/Navigator'
import { useRouter } from 'next/router'

const PagesRoute = ({ Component, pageProps }) => {

    const { colorPalette } = useAppContext()
    const removePadding = Component.noPadding;
    const router = useRouter()
    const { asPath } = router
    const parts = asPath.split('/');
    const lastPart = parts[parts.length - 1];
    const lastPart2 = parts[parts.length - 2];
    const noShowHeaderMenu = lastPart2 == 'consultation' && lastPart != 'list';


    return (
        <>
            <Head>
                <title>Afectu</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta charset="utf-8" />
                <link rel="icon" href="https://minhaclinicatrindade.s3.amazonaws.com/Afectu+-+PNG+-+Fundo+Tranparente-8%402x.png" />
            </Head>
            <ProtectRoute>
                <Box sx={{ ...styles.bodyContainer, backgroundColor: colorPalette.primary }}>
                    <LeftMenu />
                    <TabNavigator />
                    {!noShowHeaderMenu && <UserHeader />}
                    <Box sx={{
                        ...styles.contentContainer, backgroundColor: colorPalette.primary, transition: 'background-color 1s',
                        padding: removePadding ? '0px' : { xs: `30px 5px 85px 5px`, xm: `25px`, md: `120px 65px`, lg: `120px 65px` }
                    }}>
                        <Component {...pageProps} />
                    </Box>
                </Box>
            </ProtectRoute>
        </>
    )
}

const styles = {
    bodyContainer: {
        display: "flex",
        minHeight: "100vh",
        flexDirection: "row",
        width: '100%',
    },
    contentContainer: {
        display: "flex",
        width: '100%',
        flexDirection: 'column',
        flex: 1,
        gap: `35px`,
        paddingBottom: `60px`,
        overflowY: 'hidden',
        marginTop: { xs: `60px`, xm: `0px`, md: `0px`, lg: `0px` }
    },
}

export default PagesRoute;