import React, { useEffect, useState } from "react";
import { useAppContext } from "../../context/AppContext";
import { Box, ContentContainer, Text, Divider, Button, TextInput } from "../../atoms";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image"
import { api } from "../../api/api";

function CalendarIntegrate() {
    const [googleAgendaId, setGoogleAgendaId] = useState('')
    const { colorPalette, alert, setLoading, user } = useAppContext();

    useEffect(() => {
        document.title = `Afectu - Integração com Google`;
    }, []);

    const copyToClipboard = () => {
        navigator.clipboard.writeText('afectu@linear-aviary-429723-j5.iam.gserviceaccount.com')
            .then(() => {
                alert.info('Link copiado para a área de transferência!');
            })
            .catch(err => {
                console.error('Erro ao copiar o link: ', err);
            });
    };

    const handleUpadateGoogleAgendaId = async () => {
        setLoading(true)
        try {
            const response = await api.patch(`/user/update-calendar-id/${user?.id}`, { calendarId: googleAgendaId })
            if (response?.status === 200) {
                alert.success('ID da agenda atualizada.');
                return
            }
            alert.error('Tivemos um problema ao atualizar o ID de sua agenda.');
        } catch (error) {
            console.log(error)
            alert.error('Tivemos um problema ao atualizar o ID de sua agenda.');
        } finally {
            setLoading(false)
        }
    }

    return (
        <>
            <Head>
                <title>Afectu - Integração com Google</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                    rel="icon"
                    href="https://minhaclinicatrindade.s3.amazonaws.com/Afectu+-+PNG+-+Fundo+Tranparente-8%402x.png"
                />
            </Head>

            <Box
                sx={{
                    display: "flex",
                    backgroundColor: colorPalette.primary,
                    justifyContent: "center",
                    alignItems: "center",
                    width: "100%",
                    padding: "2rem",
                }}
            >
                <ContentContainer>
                    <Text bold title>
                        Passo a Passo de integração com sua Agenda Google
                    </Text>
                    <Divider />

                    <Text bold large>
                        Siga as instruções abaixo para integrar com sua Agenda do Google
                    </Text>

                    <Text bold>1. Abrir as opções de sua agenda</Text>
                    <Box sx={{ display: 'flex', justifyContent: 'flex-start', padding: '1rem' }}>
                        <Image
                            width={200}
                            height={300}
                            src="/images/primeira_etapa.png"
                            alt="Abrir opções da agenda"
                            style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)' }}
                        />
                    </Box>
                    <Text>
                        Em sua lateral esquerda, você tem uma lista de "Minhas agendas", clique nos pontinho para abrir as opções.
                    </Text>

                    <Text bold>2. Abra as configurações de compartilhamento</Text>
                    <Box sx={{ display: 'flex', justifyContent: 'flex-start', padding: '1rem' }}>
                        <Image
                            width={400}
                            height={300}
                            src="/images/segunda_etapa.png"
                            alt="Configurações de compartilhamento"
                            style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)' }}
                        />
                    </Box>

                    <Text>
                        Após abrir o modal, clique na opção de <strong>"Configurações e compart"</strong>.
                    </Text>

                    <Text bold>3. Adicione o nosso e-mail para edição de sua agenda.</Text>
                    <Box sx={{ display: 'flex', justifyContent: 'center', padding: '1rem' }}>
                        <Image
                            width={600}
                            height={400}
                            src="/images/terceira_etapa.png"
                            alt="Adição de email"
                            style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)' }}
                        />
                    </Box>

                    <Text>
                        Adicione o e-mail abaixo, e coloque a opção de "Fazer alterações e gerenciar compartilhamentos". Dessa forma, nos obtemos o privilégio para criar eventos em sua agenda.
                    </Text>

                    <Box sx={{ display: 'flex', gap: 1 }}>
                        <Box sx={{
                            display: 'flex', padding: '10px', borderRadius: 2, backgroundColor: '#f0f0f0', alignItems: 'center',
                            justifyContent: 'center'
                        }}>
                            <Text light>e-mail para integração: <strong>afectu@linear-aviary-429723-j5.iam.gserviceaccount.com</strong></Text>
                        </Box>
                        <Box sx={{
                            backgroundSize: 'cover',
                            backgroundImage: `url('/icons/copy.png')`,
                            width: 22,
                            height: 22,
                            "&:hover": { cursor: 'pointer', opacity: 0.8 }
                        }} onClick={() => copyToClipboard()} />
                    </Box>

                    <Text bold>4. Insira no campo abaixo o id de sua agenda.</Text>
                    <Box sx={{ display: 'flex', justifyContent: 'center', padding: '1rem' }}>
                        <Image
                            width={600}
                            height={400}
                            src="/images/quarta_etapa.png"
                            alt="Inserir ID da Agenda"
                            style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)' }}
                        />
                    </Box>

                    <Text>
                        Por fim, para saber em qual agenda vamos criar os eventos, copie seu <strong>ID da Agenda</strong>, cole no campo abaixo e salve.
                    </Text>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>

                        <TextInput fullWidth style={{ maxWidth: 400 }} placeholder='ID da agenda' name='google_calendar_id' onChange={(e) => setGoogleAgendaId(e.target.value)} value={googleAgendaId || ''} />
                        <Button
                            text="Salvar"
                            style={{ height: 40 }}
                            onClick={handleUpadateGoogleAgendaId}
                        />
                    </Box>

                    <Text>
                        E tudo certo! Agora, suas próximas agendas estaram vinculadas ao seu google agenda.
                    </Text>

                </ContentContainer>
            </Box>
        </>
    );
}

export default CalendarIntegrate;
